-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'athlete'
        CHECK (role IN ('athlete', 'coach', 'admin')),
    is_active BOOLEAN DEFAULT TRUE,
    name VARCHAR(100),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

-- =========================
-- USER PROFILES
-- =========================
CREATE TABLE user_profiles (
    user_id BIGINT PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    gender VARCHAR(20),
    birth_date DATE,
    height_cm NUMERIC(5,2),
    weight_kg NUMERIC(5,2),
    preferred_unit VARCHAR(10) DEFAULT 'metric',
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================
-- TRAINING TYPES
-- =========================
CREATE TABLE training_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT
);

-- =========================
-- LOCATIONS
-- =========================
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

-- =========================
-- TRAINING SESSIONS
-- =========================
CREATE TABLE training_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    training_type_id INT NOT NULL,
    start_location_id BIGINT,
    end_location_id BIGINT,

    distance_km NUMERIC(6,2) CHECK (distance_km >= 0),
    duration_seconds INT NOT NULL CHECK (duration_seconds > 0),

    temperature_c NUMERIC(4,1),
    training_date DATE NOT NULL,
    notes TEXT,

    start_point TEXT,
    end_point TEXT,
    altitude NUMERIC(6,2),
    temperature NUMERIC(4,1),
    avg_speed NUMERIC(6,2),
    avg_pace NUMERIC(6,2),

    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (training_type_id) REFERENCES training_types(id),
    FOREIGN KEY (start_location_id) REFERENCES locations(id),
    FOREIGN KEY (end_location_id) REFERENCES locations(id)
);

-- =========================
-- SESSION ROUTES
-- =========================
CREATE TABLE session_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    altitude NUMERIC(6,2),
    recorded_at TIMESTAMP NOT NULL,

    FOREIGN KEY (session_id) REFERENCES training_sessions(id) ON DELETE CASCADE
);

-- =========================
-- KILOMETER SPLITS
-- =========================
CREATE TABLE kilometer_splits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    kilometer_number INT NOT NULL CHECK (kilometer_number > 0),
    split_seconds INT NOT NULL CHECK (split_seconds > 0),

    UNIQUE (session_id, kilometer_number),

    FOREIGN KEY (session_id) REFERENCES training_sessions(id) ON DELETE CASCADE
);

-- =========================
-- PERFORMANCE METRICS
-- =========================
CREATE TABLE performance_metrics (
    session_id BIGINT PRIMARY KEY,
    avg_speed_kmh NUMERIC(5,2),
    avg_pace_seconds INT,
    calories_burned INT,
    vo2_estimate NUMERIC(5,2),
    created_at TIMESTAMP DEFAULT now(),

    FOREIGN KEY (session_id) REFERENCES training_sessions(id) ON DELETE CASCADE
);

-- =========================
-- WEEKLY SUMMARIES
-- =========================
CREATE TABLE weekly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,

    total_distance_km NUMERIC(7,2),
    total_duration_seconds INT,
    total_sessions INT,

    created_at TIMESTAMP DEFAULT now(),

    UNIQUE (user_id, week_start_date),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================
-- AUDIT LOGS
-- =========================
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100),
    entity_id BIGINT,
    created_at TIMESTAMP DEFAULT now(),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- =========================
-- INDEXES
-- =========================
CREATE INDEX idx_sessions_user ON training_sessions(user_id);
CREATE INDEX idx_sessions_date ON training_sessions(training_date);
CREATE INDEX idx_routes_session ON session_routes(session_id);
CREATE INDEX idx_splits_session ON kilometer_splits(session_id);
CREATE INDEX idx_summary_user ON weekly_summaries(user_id);